import sys
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if root not in sys.path:
    sys.path.append(root)

import numpy as np
import pandas as pd
from utilities.settings import Params, Paths

params = Params()
paths = Paths()

###############################################################################
# Utilities
###############################################################################


def topdown(iterator, language, path):
    # shitty function that just retrieve already computed raw-features generated by the parser
    name = os.path.basename(os.path.splitext(path)[0])
    run_name = name.split('_')[-1] # extract the name of the run
    run_nb = run_name[-1]
    data = pd.read_csv(os.path.join(paths.path2data, 'text', language, 'PARSER', '{}_topdown.csv'.format(run_nb)))
    return data['amplitude'].values


def bottomup(iterator, language, path):
    # shitty function that just retrieve already computed raw-features generated by the parser
    name = os.path.basename(os.path.splitext(path)[0])
    run_name = name.split('_')[-1] # extract the name of the run
    run_nb = run_name[-1]
    data = pd.read_csv(os.path.join(paths.path2data, 'text', language, 'PARSER', '{}_bottomup.csv'.format(run_nb)))
    return data['amplitude'].values
