def load_surnames():
    surnames = {'attention-layer-4-head-10': 'L4-H10', 
            'attention-layer-6-head-7': 'L6-H7', 
            'attention-layer-7-head-6': 'L7-H6', 
            'attention-layer-8-head-1': 'L8-H1', 
            'attention-layer-8-head-10': 'L8-H10', 
            'attention-layer-8-head-11': 'L8-H11', 
            'attention-layer-8-head-2': 'L8-H2', 
            'attention-layer-9-head-6': 'L9-H6',
            'attention-layer-1': 'A-L1', 
            'attention-layer-10': 'A-L10', 
            'attention-layer-11': 'A-L11', 
            'attention-layer-12': 'A-L12', 
            'attention-layer-2': 'A-L2', 
            'attention-layer-3': 'A-L3', 
            'attention-layer-4': 'A-L4', 
            'attention-layer-5': 'A-L5', 
            'attention-layer-6': 'A-L6', 
            'attention-layer-7': 'A-L7', 
            'attention-layer-8': 'A-L8', 
            'attention-layer-9': 'A-L9',
            'hidden-layer-1': 'H-L1', 
            'hidden-layer-10': 'H-L10',  
            'hidden-layer-11': 'H-L11',  
            'hidden-layer-0': 'H-L0', 
            'hidden-layer-12': 'H-L12',
            'hidden-layer-2': 'H-L2', 
            'hidden-layer-3': 'H-L3', 
            'hidden-layer-4': 'H-L4',
            'hidden-layer-5': 'H-L5',
            'hidden-layer-6': 'H-L6',
            'hidden-layer-7': 'H-L7',
            'hidden-layer-8': 'H-L8',
            'hidden-layer-9': 'H-L9',
            'word_position': 'Word-position',
                'wordrate': 'Wordrate',
                'log_frequency': 'Log-frequency',
                'function_words': 'Function-words',
               'content-words': 'Content-words',
                'wordrate_all_model': 'All-word-related-models',
                'topdown_model': 'Topdown-parser',
                'rms': 'RMS',
                'other_sentence_onset': 'Sentence-onset',
                'mfcc': 'MFCC',
                'gpt2_hidden-layer-9': 'GPT2-H-L9',
                'gpt2_hidden-layer-8': 'GPT2-H-L8',
                'gpt2_hidden-layer-7': 'GPT2-H-L7',
                'gpt2_hidden-layer-6': 'GPT2-H-L6',
                'gpt2_hidden-layer-5': 'GPT2-H-L5',
                'gpt2_hidden-layer-4': 'GPT2-H-L4',
                'gpt2_hidden-layer-3': 'GPT2-H-L3',
                'gpt2_hidden-layer-2': 'GPT2-H-L2',
                'gpt2_hidden-layer-12': 'GPT2-H-L12',
                'gpt2_hidden-layer-11': 'GPT2-H-L11',
                'gpt2_hidden-layer-10': 'GPT2-H-L10',
                'gpt2_hidden-layer-1': 'GPT2-H-L1',
                'gpt2_embeddings': 'GPT2-L0',
                'gpt2_all-hidden-layers': 'GPT2-all-hidden',
                'bottomup_model': 'Bottomup-parser',
                'bert_bucket_median_all-layers': 'BERT-median-all',
                'bert_bucket_layer-9': 'BERT-L9',
                'bert_bucket_layer-8': 'BERT-L8',
                'bert_bucket_layer-7': 'BERT-L7',
                'bert_bucket_layer-6': 'BERT-L6',
                'bert_bucket_layer-5': 'BERT-L5',
                'bert_bucket_layer-4': 'BERT-L4',
                'bert_bucket_layer-3': 'BERT-L3',
                'bert_bucket_layer-2': 'BERT-L2',
                'bert_bucket_layer-12': 'BERT-L12',
                'bert_bucket_layer-11': 'BERT-L11',
                'bert_bucket_layer-10': 'BERT-L10',
                'bert_bucket_layer-1': 'BERT-L1',
                'bert_bucket_embeddings': 'BERT-L0',
                'bert_bucket_all-layers': 'BERT-all',
                'glove_embeddings': 'GloVe',
                'lstm_wikikristina_embedding-size_600_nhid_768_nlayers_1_dropout_02_hidden_first-layer': 'LSTM-E600-H768-#L1-all',
                'lstm_wikikristina_embedding-size_600_nhid_300_nlayers_1_dropout_02_hidden_first-layer': 'LSTM-E600-H300-#L1-all',
                'lstm_wikikristina_embedding-size_600_nhid_150_nlayers_2_dropout_02_hidden_all-layers': 'LSTM-E600-H150-#L2-all',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_hidden_all-layers': 'LSTM-E600-H100-#L3-all',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_hidden_all-layers': 'LSTM-E600-H75-#L4-all',
                'lstm_wikikristina_embedding-size_600_nhid_150_nlayers_2_dropout_02_hidden_first-layer': 'LSTM-E600-H150-#L2-L1',
                'lstm_wikikristina_embedding-size_600_nhid_150_nlayers_2_dropout_02_hidden_second-layer': 'LSTM-E600-H150-#L2-L2',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_hidden_first-layer': 'LSTM-E600-H100-#L3-L1',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_hidden_second-layer': 'LSTM-E600-H100-#L3-L2',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_hidden_third-layer': 'LSTM-E600-H100-#L3-L3',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_hidden_first-layer': 'LSTM-E600-H75-#L4-L1',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_hidden_second-layer': 'LSTM-E600-H75-#L4-L2',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_hidden_third-layer': 'LSTM-E600-H75-#L4-L3',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_hidden_fourth-layer': 'LSTM-E600-H75-#L4-L4',
                'lstm_wikikristina_embedding-size_600_nhid_768_nlayers_1_dropout_02_cell_first-layer': 'LSTM-E600-C768-#L1-all',
                'lstm_wikikristina_embedding-size_600_nhid_300_nlayers_1_dropout_02_cell_first-layer': 'LSTM-E600-C300-#L1-all',
                'lstm_wikikristina_embedding-size_600_nhid_150_nlayers_2_dropout_02_cell_all-layers': 'LSTM-E600-C150-#L2-all',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_cell_all-layers': 'LSTM-E600-C100-#L3-all',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_cell_all-layers': 'LSTM-E600-C75-#L4-all',
                'lstm_wikikristina_embedding-size_600_nhid_150_nlayers_2_dropout_02_cell_first-layer': 'LSTM-E600-C150-#L2-L1',
                'lstm_wikikristina_embedding-size_600_nhid_150_nlayers_2_dropout_02_cell_second-layer': 'LSTM-E600-C150-#L2-L2',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_cell_first-layer': 'LSTM-E600-C100-#L3-L1',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_cell_second-layer': 'LSTM-E600-C100-#L3-L2',
                'lstm_wikikristina_embedding-size_600_nhid_100_nlayers_3_dropout_02_cell_third-layer': 'LSTM-E600-C100-#L3-L3',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_cell_first-layer': 'LSTM-E600-C75-#L4-L1',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_cell_second-layer': 'LSTM-E600-C75-#L4-L2',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_cell_third-layer': 'LSTM-E600-C75-#L4-L3',
                'lstm_wikikristina_embedding-size_600_nhid_75_nlayers_4_dropout_02_cell_fourth-layer': 'LSTM-E600-C75-#L4-L4',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_cell_unit_775': 'LSTM-E650-H650-Cu775',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_cell_unit_775_987': 'LSTM-E650-H650-Cu775-987',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_cell_unit_987': 'LSTM-E650-H650-Cu987',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_forget_unit_775': 'LSTM-E650-H650-Fu775',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_forget_unit_987': 'LSTM-E650-H650-Fu775',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_hidden_short-range-units': 'LSTM-E650-H650-Short-Range',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_hidden_unit_1149': 'LSTM-E650-H650-Hu1149',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_input_unit_775': 'LSTM-E650-H650-Iu775',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_input_unit_987': 'LSTM-E650-H650-Iu987',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_forget_unit_775_987': 'LSTM-E650-H650-Fu775-987',
                'lstm_wikikristina_embedding-size_650_nhid_650_nlayers_2_dropout_02_hidden_unit_1282_1283': 'LSTM-E650-H650-Hu1282-1283',
                'bert_bucket_pca_300_all-layers': 'BERT-all-pca-300',
                'gpt2_pca_300_all-layers':'GPT2-all-pca-300',
                'maps_r2_':'R2', 
                'maps_pearson_corr':'Pearson',
                'maps_significant_pearson_corr_with_pvalues':'Significant-Pearson', 
                'maps_significant_r2_with_pvalues':'Significant-R2',
                'Background': 'Background', 
                'Frontal Pole': 'FP', 
                'Insular Cortex': 'InsC', 
                'Superior Frontal Gyrus': 'SFG', 
                'Middle Frontal Gyrus': 'MFG', 
                'Inferior Frontal Gyrus, pars triangularis': 'IFG, pars tr.', 
                'Inferior Frontal Gyrus, pars opercularis': 'IFG, pars op.', 
                'Precentral Gyrus': 'PrG', 
                'Temporal Pole': 'TP', 
                'Superior Temporal Gyrus, anterior division': 'STG-a', 
                'Superior Temporal Gyrus, posterior division': 'STG-p', 
                'Middle Temporal Gyrus, anterior division': 'MTG-a', 
                'Middle Temporal Gyrus, posterior division': 'MTG-p', 
                'Middle Temporal Gyrus, temporooccipital part': 'MTG-toc', 
                'Inferior Temporal Gyrus, anterior division': 'ITG-a', 
                'Inferior Temporal Gyrus, posterior division': 'ITG-p', 
                'Inferior Temporal Gyrus, temporooccipital part': 'ITG-toc', 
                'Postcentral Gyrus': 'PoG', 
                'Superior Parietal Lobule': 'SPL', 
                'Supramarginal Gyrus, anterior division': 'SmG-a', 
                'Supramarginal Gyrus, posterior division': 'SmG-p', 
                'Angular Gyrus': 'AnG', 
                'Lateral Occipital Cortex, superior division': 'LOC-s', 
                'Lateral Occipital Cortex, inferior division': 'LOC-i', 
                'Intracalcarine Cortex': 'IccC', 
                'Frontal Medial Cortex': 'FMC', 
                'Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)': 'SMA', 
                'Subcallosal Cortex': 'SC', 
                'Paracingulate Gyrus': 'PCgG', 
                'Cingulate Gyrus, anterior division': 'CgG-a', 
                'Cingulate Gyrus, posterior division': 'CgG-p', 
                'Precuneous Cortex': 'PrCuG', 
                'Cuneal Cortex': 'CuC', 
                'Frontal Orbital Cortex': 'FoG', 
                'Parahippocampal Gyrus, anterior division': 'PHG-a', 
                'Parahippocampal Gyrus, posterior division': 'PHG-p', 
                'Lingual Gyrus': 'LgG', 
                'Temporal Fusiform Cortex, anterior division': 'TFuC-a', 
                'Temporal Fusiform Cortex, posterior division': 'TFuC-p', 
                'Temporal Occipital Fusiform Cortex': 'TocFucC', 
                'Occipital Fusiform Gyrus': 'OcFuC', 
                'Frontal Operculum Cortex': 'FOpC', 
                'Central Opercular Cortex': 'cOpC', 
                'Parietal Operculum Cortex': 'POpC', 
                'Planum Polare': 'PP', 
                "Heschl's Gyrus (includes H1 and H2)": 'HG', 
                'Planum Temporale': 'PT', 
                'Supracalcarine Cortex': 'SccC', 
                'Occipital Pole': 'OcP',
                'Left Frontal Pole': 'l-FP', 
                'Right Frontal Pole': 'r-FP', 
                'Left Insular Cortex': 'l-InsC', 
                'Right Insular Cortex': 'r-InsC', 
                'Left Superior Frontal Gyrus': 'l-SFG', 
                'Right Superior Frontal Gyrus': 'r-SFG', 
                'Left Middle Frontal Gyrus': 'l-MFG', 
                'Right Middle Frontal Gyrus': 'r-MFG', 
                'Left Inferior Frontal Gyrus, pars triangularis': 'l-IFG, pars tr.', 
                'Right Inferior Frontal Gyrus, pars triangularis': 'r-IFG, pars tr.', 
                'Left Inferior Frontal Gyrus, pars opercularis': 'l-IFG, pars op.', 
                'Right Inferior Frontal Gyrus, pars opercularis': 'r-IFG, pars op.', 
                'Left Precentral Gyrus': 'l-PrG', 
                'Right Precentral Gyrus': 'r-PrG', 
                'Left Temporal Pole': 'l-TP', 
                'Right Temporal Pole': 'r-TP', 
                'Left Superior Temporal Gyrus, anterior division': 'l-STG-a', 
                'Right Superior Temporal Gyrus, anterior division': 'r-STG-a', 
                'Left Superior Temporal Gyrus, posterior division': 'l-STG-p', 
                'Right Superior Temporal Gyrus, posterior division': 'r-STG-p', 
                'Left Middle Temporal Gyrus, anterior division': 'l-MTG-a',
                'Right Middle Temporal Gyrus, anterior division': 'r-MTG-a',
                'Left Middle Temporal Gyrus, posterior division': 'l-MTG-p',
                'Right Middle Temporal Gyrus, posterior division': 'r-MTG-p',
                'Left Middle Temporal Gyrus, temporooccipital part': 'l-MTG-toc', 
                'Right Middle Temporal Gyrus, temporooccipital part': 'r-MTG-toc', 
                'Left Inferior Temporal Gyrus, anterior division': 'l-ITG-a', 
                'Right Inferior Temporal Gyrus, anterior division': 'r-ITG-a', 
                'Left Inferior Temporal Gyrus, posterior division': 'l-ITG-p', 
                'Right Inferior Temporal Gyrus, posterior division': 'r-ITG-p', 
                'Left Inferior Temporal Gyrus, temporooccipital part': 'l-ITG-toc', 
                'Right Inferior Temporal Gyrus, temporooccipital part': 'r-ITG-toc', 
                'Left Postcentral Gyrus': 'l-PoG', 
                'Right Postcentral Gyrus': 'r-PoG', 
                'Left Superior Parietal Lobule': 'l-SPL', 
                'Right Superior Parietal Lobule': 'r-SPL', 
                'Left Supramarginal Gyrus, anterior division': 'l-SmG-a', 
                'Right Supramarginal Gyrus, anterior division': 'r-SmG-a', 
                'Left Supramarginal Gyrus, posterior division': 'l-SmG-p', 
                'Right Supramarginal Gyrus, posterior division': 'r-SmG-p', 
                'Left Angular Gyrus': 'l-AnG', 
                'Right Angular Gyrus': 'r-AnG', 
                'Left Lateral Occipital Cortex, superior division': 'l-LOC-s', 
                'Right Lateral Occipital Cortex, superior division': 'r-LOC-s', 
                'Left Lateral Occipital Cortex, inferior division': 'l-LOC-i', 
                'Right Lateral Occipital Cortex, inferior division': 'r-LOC-i', 
                'Left Intracalcarine Cortex': 'l-IccC', 
                'Right Intracalcarine Cortex': 'r-IccC', 
                'Left Frontal Medial Cortex': 'l-FMC', 
                'Right Frontal Medial Cortex': 'r-FMC', 
                'Left Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)': 'l-SMA', 
                'Right Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)': 'r-SMA', 
                'Left Subcallosal Cortex': 'l-SC', 
                'Right Subcallosal Cortex': 'r-SC', 
                'Left Paracingulate Gyrus': 'l-PCgG', 
                'Right Paracingulate Gyrus': 'r-PCgG', 
                'Left Cingulate Gyrus, anterior division': 'l-CgG-a', 
                'Right Cingulate Gyrus, anterior division': 'r-CgG-a', 
                'Left Cingulate Gyrus, posterior division': 'l-CgG-p', 
                'Right Cingulate Gyrus, posterior division': 'r-CgG-p', 
                'Left Precuneous Cortex': 'l-PrCuG', 
                'Right Precuneous Cortex': 'r-PrCuG', 
                'Left Cuneal Cortex': 'l-CuC', 
                'Right Cuneal Cortex': 'r-CuC', 
                'Left Frontal Orbital Cortex': 'l-FoG', 
                'Right Frontal Orbital Cortex': 'r-FoG', 
                'Left Parahippocampal Gyrus, anterior division': 'l-PHG-a', 
                'Right Parahippocampal Gyrus, anterior division': 'r-PHG-a', 
                'Left Parahippocampal Gyrus, posterior division': 'l-PHG-p', 
                'Right Parahippocampal Gyrus, posterior division': 'r-PHG-p', 
                'Left Lingual Gyrus': 'l-LgG', 
                'Right Lingual Gyrus': 'r-LgG', 
                'Left Temporal Fusiform Cortex, anterior division': 'l-TFuC-a', 
                'Right Temporal Fusiform Cortex, anterior division': 'r-TFuC-a', 
                'Left Temporal Fusiform Cortex, posterior division': 'l-TFuC-p', 
                'Right Temporal Fusiform Cortex, posterior division': 'r-TFuC-p', 
                'Left Temporal Occipital Fusiform Cortex': 'l-TocFucC', 
                'Right Temporal Occipital Fusiform Cortex': 'r-TocFucC', 
                'Left Occipital Fusiform Gyrus': 'l-OcFuC', 
                'Right Occipital Fusiform Gyrus': 'r-OcFuC', 
                'Left Frontal Operculum Cortex': 'l-FOpC', 
                'Right Frontal Operculum Cortex': 'r-FOpC', 
                'Left Central Opercular Cortex': 'l-cOpC', 
                'Right Central Opercular Cortex': 'r-cOpC', 
                'Left Parietal Operculum Cortex': 'l-POpC', 
                'Right Parietal Operculum Cortex': 'r-POpC', 
                'Left Planum Polare': 'l-PP', 
                'Right Planum Polare': 'r-PP', 
                "Left Heschl's Gyrus (includes H1 and H2)": 'l-HG', 
                "Right Heschl's Gyrus (includes H1 and H2)": 'r-HG', 
                'Left Planum Temporale': 'l-PT', 
                'Right Planum Temporale': 'r-PT', 
                'Left Supracalcarine Cortex': 'l-SccC', 
                'Right Supracalcarine Cortex': 'r-SccC', 
                'Left Occipital Pole': 'l-OcP',
                'Right Occipital Pole': 'r-OcP',
               }
    return surnames

def load_syntactic_roi():
    syntactic_roi = [
        'Left Inferior Frontal Gyrus, pars triangularis',
        'Left Inferior Frontal Gyrus, pars opercularis',
        'Left Temporal Pole',
        'Left Superior Temporal Gyrus, anterior division',
        'Left Superior Temporal Gyrus, posterior division',
        'Left Middle Temporal Gyrus, anterior division',
        'Left Middle Temporal Gyrus, posterior division',
        'Left Middle Temporal Gyrus, temporooccipital part',
        'Left Angular Gyrus',
        'Right Inferior Frontal Gyrus, pars triangularis',
        'Right Inferior Frontal Gyrus, pars opercularis',
        'Right Temporal Pole',
        'Right Superior Temporal Gyrus, anterior division',
        'Right Superior Temporal Gyrus, posterior division',
        'Right Middle Temporal Gyrus, anterior division',
        'Right Middle Temporal Gyrus, posterior division',
        'Right Middle Temporal Gyrus, temporooccipital part',
        'Right Angular Gyrus'
    ]
    surnames = load_surnames()
    syntactic_roi += [surnames[item] for item in syntactic_roi]
    return syntactic_roi


def load_language_roi():
    language_roi = [
        'Left Inferior Frontal Gyrus, pars triangularis',
        'Left Inferior Frontal Gyrus, pars opercularis',
        'Left Temporal Pole',
        'Left Superior Temporal Gyrus, anterior division',
        'Left Superior Temporal Gyrus, posterior division',
        'Left Middle Temporal Gyrus, anterior division',
        'Left Middle Temporal Gyrus, posterior division',
        'Left Middle Temporal Gyrus, temporooccipital part',
        'Left Angular Gyrus',
        'Right Inferior Frontal Gyrus, pars triangularis',
        'Right Inferior Frontal Gyrus, pars opercularis',
        'Right Temporal Pole',
        'Right Superior Temporal Gyrus, anterior division',
        'Right Superior Temporal Gyrus, posterior division',
        'Right Middle Temporal Gyrus, anterior division',
        'Right Middle Temporal Gyrus, posterior division',
        'Right Middle Temporal Gyrus, temporooccipital part',
        'Right Angular Gyrus'
    ]
    surnames = load_surnames()
    language_roi += [surnames[item] for item in language_roi]
    return language_roi


def load_interesting_rois():
    interesting_rois = [
        'Left Frontal Pole',
        'Right Frontal Pole',
        'Left Superior Frontal Gyrus',
        'Right Superior Frontal Gyrus',
        'Left Middle Frontal Gyrus',
        'Right Middle Frontal Gyrus',
        'Left Inferior Frontal Gyrus, pars triangularis',
        'Right Inferior Frontal Gyrus, pars triangularis',
        'Left Inferior Frontal Gyrus, pars opercularis',
        'Right Inferior Frontal Gyrus, pars opercularis',
        'Left Temporal Pole',
        'Right Temporal Pole',
        'Left Superior Temporal Gyrus, anterior division',
        'Right Superior Temporal Gyrus, anterior division',
        'Left Superior Temporal Gyrus, posterior division',
        'Right Superior Temporal Gyrus, posterior division',
        'Left Middle Temporal Gyrus, anterior division',
        'Right Middle Temporal Gyrus, anterior division',
        'Left Middle Temporal Gyrus, posterior division',
        'Right Middle Temporal Gyrus, posterior division',
        'Left Middle Temporal Gyrus, temporooccipital part',
        'Right Middle Temporal Gyrus, temporooccipital part',
        'Right Inferior Temporal Gyrus, anterior division',
        'Left Inferior Temporal Gyrus, temporooccipital part',
        'Left Supramarginal Gyrus, anterior division',
        'Left Supramarginal Gyrus, posterior division',
        'Right Supramarginal Gyrus, posterior division',
        'Left Angular Gyrus',
        'Right Angular Gyrus',
        'Left Lateral Occipital Cortex, superior division',
        'Right Lateral Occipital Cortex, superior division',
        'Left Paracingulate Gyrus',
        'Right Paracingulate Gyrus',
        'Left Cingulate Gyrus, anterior division',
        'Right Cingulate Gyrus, anterior division',
        'Left Cingulate Gyrus, posterior division',
        'Right Cingulate Gyrus, posterior division',
        'Left Precuneous Cortex',
        'Right Precuneous Cortex',
        'Left Frontal Orbital Cortex',
        'Left Frontal Operculum Cortex',
        'Right Frontal Operculum Cortex',
        'Left Parietal Operculum Cortex',
        'Left Planum Polare',
        'Right Planum Polare',
        "Left Heschl's Gyrus (includes H1 and H2)",
        "Right Heschl's Gyrus (includes H1 and H2)",
        'Left Planum Temporale',
        'Right Planum Temporale',
        'Right Occipital Pole',
    ]
    surnames = load_surnames()
    interesting_rois += [surnames[item] for item in interesting_rois]
    return interesting_rois


def load_intriguing_rois():
    intriguing_rois = [
        'Left Inferior Temporal Gyrus, anterior division',
        'Right Frontal Medial Cortex',
        'Right Frontal Orbital Cortex',
        'Left Superior Parietal Lobule',
        'Left Parahippocampal Gyrus, posterior division',
        'Right Parietal Operculum Cortex',
        'Left Frontal Medial Cortex',
        'Right Superior Parietal Lobule',
        'Right Inferior Temporal Gyrus, temporooccipital part',
        'Left Central Opercular Cortex',
        'Right Insular Cortex'
    ]
    surnames = load_surnames()
    intriguing_rois += [surnames[item] for item in intriguing_rois]
    return intriguing_rois